# fly.toml app configuration file generated for api-acmcsuf-com-black-wind-9210 on 2026-08-01T19:15:18-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'api-acmcsuf-com-black-wind-9210'
primary_region = 'lax'

[build]
  [build.args]
    GO_VERSION = '1.25.0'

[env]
  PORT = '8080'
  DATABASE_URL= 'file:/app/data/acmcsuf.db?cache=shared&mode=rwc'
  GIN_MODE = 'debug'
  ENV = 'development'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256m'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "sqlite_data"
  destination = "/app/data"
