// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlite

import (
	"database/sql"
)

type Announcement struct {
	Uuid                 string         `json:"uuid"`
	Visibility           string         `json:"visibility"`
	AnnounceAt           int64          `json:"announce_at"`
	DiscordChannelID     sql.NullString `json:"discord_channel_id"`
	DiscordMessageID     sql.NullString `json:"discord_message_id"`
}

type Event struct {
	Uuid     string      `json:"uuid"`
	Location string      `json:"location"`
	StartAt  interface{} `json:"start_at"`
	EndAt    interface{} `json:"end_at"`
	IsAllDay bool        `json:"is_all_day"`
	Host     string      `json:"host"`
}

type Person struct {
	Uuid             sql.NullString `json:"uuid"`
	Name             sql.NullString `json:"name"`
	PreferredPronoun sql.NullString `json:"preferred_pronoun"`
}