// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package sqlite

import (
	"database/sql"
)

type Event struct {
	ID         string      `json:"id"`
	Location   string      `json:"location"`
	StartAt    interface{} `json:"start_at"`
	DurationMs interface{} `json:"duration_ms"`
	IsAllDay   bool        `json:"is_all_day"`
	Host       string      `json:"host"`
	Visibility string      `json:"visibility"`
	CreatedAt  int64       `json:"created_at"`
	UpdatedAt  int64       `json:"updated_at"`
}

type Meta struct {
	V int64 `json:"v"`
}

type Resource struct {
	ID             string         `json:"id"`
	Title          string         `json:"title"`
	ContentMd      string         `json:"content_md"`
	ImageUrl       sql.NullString `json:"image_url"`
	ResourceType   string         `json:"resource_type"`
	ResourceListID sql.NullInt64  `json:"resource_list_id"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
}

type ResourceList struct {
	ID        int64  `json:"id"`
	Title     string `json:"title"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type ResourceReference struct {
	ID             int64  `json:"id"`
	ResourceID     string `json:"resource_id"`
	ResourceListID int64  `json:"resource_list_id"`
	CreatedAt      int64  `json:"created_at"`
	UpdatedAt      int64  `json:"updated_at"`
}
