// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbmodels

import (
	"database/sql"
)

type Announcement struct {
	Uuid             string         `json:"uuid"`
	Visibility       string         `json:"visibility"`
	AnnounceAt       int64          `json:"announce_at"`
	DiscordChannelID sql.NullString `json:"discord_channel_id"`
	DiscordMessageID sql.NullString `json:"discord_message_id"`
}

type Event struct {
	Uuid     string `json:"uuid"`
	Location string `json:"location"`
	StartAt  int64  `json:"start_at"`
	EndAt    int64  `json:"end_at"`
	IsAllDay bool   `json:"is_all_day"`
	Host     string `json:"host"`
}

type Officer struct {
	Uuid     string         `json:"uuid"`
	FullName string         `json:"full_name"`
	Picture  sql.NullString `json:"picture"`
	Github   sql.NullString `json:"github"`
	Discord  sql.NullString `json:"discord"`
}

type Position struct {
	Oid      string         `json:"oid"`
	Semester string         `json:"semester"`
	Tier     int64          `json:"tier"`
	FullName string         `json:"full_name"`
	Title    sql.NullString `json:"title"`
	Team     sql.NullString `json:"team"`
}

type Tier struct {
	Tier   int64          `json:"tier"`
	Title  sql.NullString `json:"title"`
	TIndex sql.NullInt64  `json:"t_index"`
	Team   sql.NullString `json:"team"`
}
