// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workshop.sql

package dbmodels

import (
	"context"
	"database/sql"
)

const createWorkshop = `-- name: CreateWorkshop :exec
INSERT INTO
workshop (
    uuid,
    title,
    team,
    semester,
    start_at,
    link
)
VALUES
(?, ?, ?, ?, ?, ?)
RETURNING uuid, title, team, semester, start_at, link
`

type CreateWorkshopParams struct {
	Uuid     int64          `json:"uuid"`
	Title    sql.NullString `json:"title"`
	Team     sql.NullString `json:"team"`
	Semester interface{}    `json:"semester"`
	StartAt  sql.NullTime   `json:"start_at"`
	Link     sql.NullString `json:"link"`
}

func (q *Queries) CreateWorkshop(ctx context.Context, arg CreateWorkshopParams) error {
	_, err := q.db.ExecContext(ctx, createWorkshop,
		arg.Uuid,
		arg.Title,
		arg.Team,
		arg.Semester,
		arg.StartAt,
		arg.Link,
	)
	return err
}

const deleteWorkshop = `-- name: DeleteWorkshop :exec
DELETE FROM workshop
WHERE uuid = ?
`

func (q *Queries) DeleteWorkshop(ctx context.Context, uuid int64) error {
	_, err := q.db.ExecContext(ctx, deleteWorkshop, uuid)
	return err
}
