// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: board.sql

package dbmodels

import (
	"context"
	"database/sql"
)

const createOfficer = `-- name: CreateOfficer :one
INSERT INTO
officer (
    uuid,
    full_name,
    picture,
    github,
    discord
)
VALUES
(?, ?, ?, ?, ?)
RETURNING uuid, full_name, picture, github, discord
`

type CreateOfficerParams struct {
	Uuid     string
	FullName string
	Picture  sql.NullString
	Github   sql.NullString
	Discord  sql.NullString
}

func (q *Queries) CreateOfficer(ctx context.Context, arg CreateOfficerParams) (Officer, error) {
	row := q.db.QueryRowContext(ctx, createOfficer,
		arg.Uuid,
		arg.FullName,
		arg.Picture,
		arg.Github,
		arg.Discord,
	)
	var i Officer
	err := row.Scan(
		&i.Uuid,
		&i.FullName,
		&i.Picture,
		&i.Github,
		&i.Discord,
	)
	return i, err
}

const createPosition = `-- name: CreatePosition :one
INSERT INTO
position (
    officer_id,
    semester,
    tier,
    full_name,
    title,
    team
)
VALUES
(?, ?, ?, ?, ?, ?)
RETURNING officer_id, semester, tier, full_name, title, team
`

type CreatePositionParams struct {
	OfficerID string
	Semester  string
	Tier      int64
	FullName  string
	Title     sql.NullString
	Team      sql.NullString
}

func (q *Queries) CreatePosition(ctx context.Context, arg CreatePositionParams) (Position, error) {
	row := q.db.QueryRowContext(ctx, createPosition,
		arg.OfficerID,
		arg.Semester,
		arg.Tier,
		arg.FullName,
		arg.Title,
		arg.Team,
	)
	var i Position
	err := row.Scan(
		&i.OfficerID,
		&i.Semester,
		&i.Tier,
		&i.FullName,
		&i.Title,
		&i.Team,
	)
	return i, err
}

const createTier = `-- name: CreateTier :one
INSERT INTO
tier (
    tier,
    title,
    t_index,
    team
)
VALUES
(?, ?, ?, ?)
RETURNING tier, title, t_index, team
`

type CreateTierParams struct {
	Tier   int64
	Title  sql.NullString
	TIndex sql.NullInt64
	Team   sql.NullString
}

func (q *Queries) CreateTier(ctx context.Context, arg CreateTierParams) (Tier, error) {
	row := q.db.QueryRowContext(ctx, createTier,
		arg.Tier,
		arg.Title,
		arg.TIndex,
		arg.Team,
	)
	var i Tier
	err := row.Scan(
		&i.Tier,
		&i.Title,
		&i.TIndex,
		&i.Team,
	)
	return i, err
}

const deleteOfficer = `-- name: DeleteOfficer :exec
DELETE FROM officer
WHERE uuid = ?
`

func (q *Queries) DeleteOfficer(ctx context.Context, uuid string) error {
	_, err := q.db.ExecContext(ctx, deleteOfficer, uuid)
	return err
}

const deletePosition = `-- name: DeletePosition :exec
DELETE FROM position
WHERE
    officer_id = ?
    AND semester = ?
    AND tier = ?
`

type DeletePositionParams struct {
	OfficerID string
	Semester  string
	Tier      int64
}

func (q *Queries) DeletePosition(ctx context.Context, arg DeletePositionParams) error {
	_, err := q.db.ExecContext(ctx, deletePosition, arg.OfficerID, arg.Semester, arg.Tier)
	return err
}

const deleteTier = `-- name: DeleteTier :exec
DELETE FROM tier
WHERE tier = ?
`

func (q *Queries) DeleteTier(ctx context.Context, tier int64) error {
	_, err := q.db.ExecContext(ctx, deleteTier, tier)
	return err
}

const getOfficer = `-- name: GetOfficer :one
SELECT
    full_name,
    picture,
    github,
    discord
FROM
    officer
WHERE
    uuid = ?
`

type GetOfficerRow struct {
	FullName string
	Picture  sql.NullString
	Github   sql.NullString
	Discord  sql.NullString
}

func (q *Queries) GetOfficer(ctx context.Context, uuid string) (GetOfficerRow, error) {
	row := q.db.QueryRowContext(ctx, getOfficer, uuid)
	var i GetOfficerRow
	err := row.Scan(
		&i.FullName,
		&i.Picture,
		&i.Github,
		&i.Discord,
	)
	return i, err
}

const getOfficers = `-- name: GetOfficers :many
SELECT
    uuid,
    full_name,
    picture,
    github,
    discord
FROM
    officer
`

func (q *Queries) GetOfficers(ctx context.Context) ([]Officer, error) {
	rows, err := q.db.QueryContext(ctx, getOfficers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Officer
	for rows.Next() {
		var i Officer
		if err := rows.Scan(
			&i.Uuid,
			&i.FullName,
			&i.Picture,
			&i.Github,
			&i.Discord,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPosition = `-- name: GetPosition :one
SELECT
    officer_id,
    semester,
    tier,
    full_name,
    title,
    team
FROM
    position
WHERE
    officer_id = ?
`

func (q *Queries) GetPosition(ctx context.Context, officerID string) (Position, error) {
	row := q.db.QueryRowContext(ctx, getPosition, officerID)
	var i Position
	err := row.Scan(
		&i.OfficerID,
		&i.Semester,
		&i.Tier,
		&i.FullName,
		&i.Title,
		&i.Team,
	)
	return i, err
}

const getPositions = `-- name: GetPositions :many
SELECT
    officer_id,
    semester,
    tier,
    full_name,
    title,
    team
FROM
    position
`

func (q *Queries) GetPositions(ctx context.Context) ([]Position, error) {
	rows, err := q.db.QueryContext(ctx, getPositions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Position
	for rows.Next() {
		var i Position
		if err := rows.Scan(
			&i.OfficerID,
			&i.Semester,
			&i.Tier,
			&i.FullName,
			&i.Title,
			&i.Team,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTier = `-- name: GetTier :one
SELECT
    tier,
    title,
    t_index,
    team
FROM
    tier
WHERE
    tier = ?
`

func (q *Queries) GetTier(ctx context.Context, tier int64) (Tier, error) {
	row := q.db.QueryRowContext(ctx, getTier, tier)
	var i Tier
	err := row.Scan(
		&i.Tier,
		&i.Title,
		&i.TIndex,
		&i.Team,
	)
	return i, err
}

const getTiers = `-- name: GetTiers :many
SELECT
    tier,
    title,
    t_index,
    team
FROM
    tier
ORDER BY
    tier
`

func (q *Queries) GetTiers(ctx context.Context) ([]Tier, error) {
	rows, err := q.db.QueryContext(ctx, getTiers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tier
	for rows.Next() {
		var i Tier
		if err := rows.Scan(
			&i.Tier,
			&i.Title,
			&i.TIndex,
			&i.Team,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOfficer = `-- name: UpdateOfficer :exec

UPDATE officer
SET
    full_name = COALESCE(?1, full_name),
    picture = COALESCE(?2, picture),
    github = COALESCE(?3, github),
    discord = COALESCE(?4, discord)
WHERE
    uuid = ?5
`

type UpdateOfficerParams struct {
	FullName string
	Picture  sql.NullString
	Github   sql.NullString
	Discord  sql.NullString
	Uuid     string
}

// NOTE: Had to declare above table as :one, may need to change later to :many
func (q *Queries) UpdateOfficer(ctx context.Context, arg UpdateOfficerParams) error {
	_, err := q.db.ExecContext(ctx, updateOfficer,
		arg.FullName,
		arg.Picture,
		arg.Github,
		arg.Discord,
		arg.Uuid,
	)
	return err
}

const updatePosition = `-- name: UpdatePosition :exec
UPDATE position
SET
    full_name = COALESCE(?1, full_name),
    title = COALESCE(?2, title),
    team = COALESCE(?3, team)
WHERE
    officer_id = ?4
    AND semester = ?5
    AND tier = ?6
`

type UpdatePositionParams struct {
	FullName  string
	Title     sql.NullString
	Team      sql.NullString
	OfficerID string
	Semester  string
	Tier      int64
}

func (q *Queries) UpdatePosition(ctx context.Context, arg UpdatePositionParams) error {
	_, err := q.db.ExecContext(ctx, updatePosition,
		arg.FullName,
		arg.Title,
		arg.Team,
		arg.OfficerID,
		arg.Semester,
		arg.Tier,
	)
	return err
}

const updateTier = `-- name: UpdateTier :exec
UPDATE tier
SET
    title = COALESCE(?1, title),
    t_index = COALESCE(?2, t_index),
    team = COALESCE(?3, team)
WHERE
    tier = ?4
`

type UpdateTierParams struct {
	Title  sql.NullString
	TIndex sql.NullInt64
	Team   sql.NullString
	Tier   int64
}

func (q *Queries) UpdateTier(ctx context.Context, arg UpdateTierParams) error {
	_, err := q.db.ExecContext(ctx, updateTier,
		arg.Title,
		arg.TIndex,
		arg.Team,
		arg.Tier,
	)
	return err
}
