// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbmodels

import (
	"database/sql"
)

type Announcement struct {
	Uuid             string
	Visibility       string
	AnnounceAt       int64
	DiscordChannelID sql.NullString
	DiscordMessageID sql.NullString
}

type Event struct {
	Uuid     string
	Location string
	StartAt  int64
	EndAt    int64
	IsAllDay bool
	Host     string
}

type Officer struct {
	Uuid     string
	FullName string
	Picture  sql.NullString
	Github   sql.NullString
	Discord  sql.NullString
}

type Position struct {
	Oid      string
	Semester string
	Tier     int64
	FullName string
	Title    sql.NullString
	Team     sql.NullString
}

type Tier struct {
	Tier   int64
	Title  sql.NullString
	TIndex sql.NullInt64
	Team   sql.NullString
}
