// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package models

import (
	"database/sql"
)

type Announcement struct {
	Uuid             string         `json:"uuid"`
	Visibility       string         `json:"visibility"`
	AnnounceAt       int64          `json:"announce_at"`
	DiscordChannelID sql.NullString `json:"discord_channel_id"`
	DiscordMessageID sql.NullString `json:"discord_message_id"`
}

type BoardMember struct {
	ID      interface{}    `json:"id"`
	Name    string         `json:"name"`
	Branch  string         `json:"branch"`
	Github  sql.NullString `json:"github"`
	Discord sql.NullString `json:"discord"`
	Year    sql.NullInt64  `json:"year"`
	Bio     sql.NullString `json:"bio"`
}

type Branch struct {
	Name string `json:"name"`
}

type Event struct {
	Uuid     string      `json:"uuid"`
	Location string      `json:"location"`
	StartAt  interface{} `json:"start_at"`
	EndAt    interface{} `json:"end_at"`
	IsAllDay bool        `json:"is_all_day"`
	Host     string      `json:"host"`
}

type MemberOf struct {
	Bmid  interface{} `json:"bmid"`
	Bname string      `json:"bname"`
}

type Person struct {
	Uuid             string         `json:"uuid"`
	Name             sql.NullString `json:"name"`
	PreferredPronoun sql.NullString `json:"preferred_pronoun"`
}
