// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package models

import (
	"context"
	"database/sql"
)

const createAnnouncement = `-- name: CreateAnnouncement :exec
INSERT INTO
announcement (
    uuid,
    visibility,
    announce_at,
    discord_channel_id,
    discord_message_id
)
VALUES
(?, ?, ?, ?, ?)
`

type CreateAnnouncementParams struct {
	Uuid             string         `json:"uuid"`
	Visibility       string         `json:"visibility"`
	AnnounceAt       int64          `json:"announce_at"`
	DiscordChannelID sql.NullString `json:"discord_channel_id"`
	DiscordMessageID sql.NullString `json:"discord_message_id"`
}

func (q *Queries) CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) error {
	_, err := q.db.ExecContext(ctx, createAnnouncement,
		arg.Uuid,
		arg.Visibility,
		arg.AnnounceAt,
		arg.DiscordChannelID,
		arg.DiscordMessageID,
	)
	return err
}

const createEvent = `-- name: CreateEvent :exec
INSERT INTO
event (
    uuid,
    location,
    start_at,
    end_at,
    is_all_day,
    host
    -- the following doens't exist in schema
    -- visibility
)
VALUES
(?, ?, ?, ?, ?, ?)
`

type CreateEventParams struct {
	Uuid     string      `json:"uuid"`
	Location string      `json:"location"`
	StartAt  interface{} `json:"start_at"`
	EndAt    interface{} `json:"end_at"`
	IsAllDay bool        `json:"is_all_day"`
	Host     string      `json:"host"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.ExecContext(ctx, createEvent,
		arg.Uuid,
		arg.Location,
		arg.StartAt,
		arg.EndAt,
		arg.IsAllDay,
		arg.Host,
	)
	return err
}

const createPerson = `-- name: CreatePerson :exec
INSERT INTO
person (uuid, name, preferred_pronoun)
VALUES
(?, ?, ?)
`

type CreatePersonParams struct {
	Uuid             string         `json:"uuid"`
	Name             sql.NullString `json:"name"`
	PreferredPronoun sql.NullString `json:"preferred_pronoun"`
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) error {
	_, err := q.db.ExecContext(ctx, createPerson, arg.Uuid, arg.Name, arg.PreferredPronoun)
	return err
}

const getAnnouncement = `-- name: GetAnnouncement :exec
SELECT
    uuid,
    visibility,
    announce_at,
    discord_channel_id,
    discord_message_id
FROM
    announcement
WHERE
    uuid = ?
`

func (q *Queries) GetAnnouncement(ctx context.Context, uuid string) error {
	_, err := q.db.ExecContext(ctx, getAnnouncement, uuid)
	return err
}

const getEvent = `-- name: GetEvent :exec
SELECT
    uuid,
    location,
    start_at,
    end_at,
    is_all_day,
    host
    -- the following does not exist in schema
    -- visibility
FROM
    event
WHERE
    uuid = ?
`

func (q *Queries) GetEvent(ctx context.Context, uuid string) error {
	_, err := q.db.ExecContext(ctx, getEvent, uuid)
	return err
}

const getPerson = `-- name: GetPerson :exec
SELECT
    uuid,
    name,
    preferred_pronoun
FROM
    person
WHERE
    uuid = ?
`

func (q *Queries) GetPerson(ctx context.Context, uuid string) error {
	_, err := q.db.ExecContext(ctx, getPerson, uuid)
	return err
}
